### ISSUE TITLE
PAL exported template cannot be created as new User Defined Data Collector Set

### ISSUE THREAD

**Issue by bulentozkir** [clinthuffman/PAL#26]
The XML template file exported by PAL cannot be parsed by Perfmon as new User Defined Data Collector set due to incorrect Display Name and Description sections.

**Comment by jeffstokes72** [comment]
Which specific xml template is this? I assume 2.8.x?

**Comment by jeffstokes72** [comment]
Yeah sorry had to edit my post, github flavored markdown was never my strong suit

**Comment by bulentozkir** [comment]
When I edit the following 2 lines 

**<DisplayName>@%systemroot%\system32\wdc.dll,#10026</DisplayName>
<Description>@%systemroot%\system32\wdc.dll,#10027</Description>**

and replace values with static regular simple text, import is successful. There is a workaround yet I wanted to inform you anyhow. Regards.

**Comment by jeffstokes72** [comment]
Cool yeah, I was just testing it as well to help Clint understand the issue easily. Plus I figured I could reply since he's not awake yet :)

Thanks for making your issues here in GitHub for the project!

**Comment by clinthuffman** [comment]
Right, I'll fix the encoding. Also, I think the best approach is to remove anything that is not necessary. In this case, the two lines that Bulent mentioned can be removed in the templates. I'll spend some time on this and get a proper fix soon. Thanks guys!

**Comment by clinthuffman** [comment]
Okay, I fixed the exporter so that the XML templates work in Performance Monitor now. At this point, the SQL threshold files need to be updated to have the proper counter paths. I have asked the original content owner to do the updates. The fixes will be in 2.8.2. In the meantime as a workaround, remove the DisplayName and Description XML nodes from the template file.

Also, consider downloading and using the PAL Collector script at http://aka.ms/PalCollector. It will automatically create a Performance Monitor data collector with all of the counter objects that PAL analyzes. This includes SQL counters and SQL named instances.

**Comment by clinthuffman** [comment]
Fixed in 2.8.2. Please keep in mind that the content owners still need to fix their respective threshold files.

**Comment by clinthuffman** [comment]
Fixed in 2.8.2.
